# Based on
# > $Id: t-williams.conf,v 1.1 2009-11-02 18:59:28 nicm Exp $
# >
# > ~/.tmux.conf - tmux terminal multiplexer config
# > Thayer Williams (http://cinderwick.ca)
# > "Feel free to do whatever you like with it."

# Needing to press C-a twice in vim is irritating due to its dissimilarity with
# C-x which only needs to be pressed once, so it's better to use some binding
# which doesn't have a symmetrical one anywhere.
unbind C-b
set -g prefix C-g
# send the prefix to client inside window (ala nested sessions)
bind-key C-g send-prefix

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# ctrl+left/right cycles thru windows
bind-key -n C-right next
bind-key -n C-left prev

# quick view of processes
bind '~' split-window "exec htop"

# ESC works faster
set -sg escape-time 10

setw -g mode-keys vi
