theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {speed_up;K*b}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "backlight"
device = "amdgpu_bl0"

[[block]]
block = "sound"
show_volume_when_muted = true
step_width = 3

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
